Removing loop due to asynchronous executions while the functions still running in loop

diff --git a/linux/systems/bin/dotfiles-post-setup b/linux/systems/bin/dotfiles-post-setup
--- a/linux/systems/bin/dotfiles-post-setup
+++ b/linux/systems/bin/dotfiles-post-setup
@@ -1,7 +1,6 @@
 #!/bin/sh
 
 WORKFILES_DIR="linux/systems/bin"
-WORKFILES="dotfiles-python dotfiles-nodejs dotfiles-php dotfiles-java-sdkman dotfiles-ruby dotfiles-vim dotfiles-git"
 WORKDIR=$(mktemp -d)
 
 setup_directory() {
@@ -9,28 +8,27 @@ setup_directory() {
     trap 'rm -rf "$WORKDIR"' EXIT
     echo "Copying files to $WORKDIR ..."
     cd $WORKFILES_DIR
-    for SCRIPT in $WORKFILES; do
-        cp -r "$SCRIPT" "$WORKDIR"
-    done
-    ls -lah "$WORKDIR"
+    cp -r "dotfiles-python" "$WORKDIR"
+    cp -r "dotfiles-nodejs" "$WORKDIR"
+    cp -r "dotfiles-php" "$WORKDIR"
+    cp -r "dotfiles-java-sdkman" "$WORKDIR"
+    cp -r "dotfiles-ruby" "$WORKDIR"
+    cp -r "dotfiles-vim" "$WORKDIR"
+    cp -r "dotfiles-git" "$WORKDIR"
     echo "Changing to $WORKDIR ..."
     cd "$WORKDIR"
-    echo "Checking for required scripts..."
-    for SCRIPT in $WORKFILES; do
-        check_script $SCRIPT
-    done
 }
 
-check_script() {
-    local script_name=$1
-    echo "Checking for $script_name..."
-    if [ ! -f "$WORKDIR/$script_name" ]; then
-        echo "Error: $script_name not found in the current directory ($PWD)" >&2
-        exit 1
-    else
-        echo "$script_name found."
-    fi
-}
+# check_script() {
+#     local script_name=$1
+#     echo "Checking for $script_name..."
+#     if [ ! -f "$WORKDIR/$script_name" ]; then
+#         echo "Error: $script_name not found in the current directory ($PWD)" >&2
+#         exit 1
+#     else
+#         echo "$script_name found."
+#     fi
+# }
 
 prompt_installation() {
     local name=$1
@@ -53,8 +51,9 @@ prompt_installation() {
 }
 
 main() {
+    ls -lah "$WORKDIR"
+
     echo 'Setting up git flow...'
-    check_script "$WORKDIR/dotfiles-git"
     sh $WORKDIR/dotfiles-git
 
     echo "Symlinking state dir..."
@@ -90,12 +89,12 @@ main() {
     echo 'Setting up Antigen...'
     curl -L https://git.io/antigen >"$HOME/antigen.zsh"
 
-    prompt_installation "python with pyenv" "python"
-    prompt_installation "Ruby with rbenv" "ruby"
-    prompt_installation "SDKMAN" "" "java"
-    prompt_installation "NodeJS with NVM" "nodejs"
-    prompt_installation "PHP with phpenv" "php"
-    prompt_installation "Vim with plugins" "vim"
+    prompt_installation "python with pyenv" "dotfiles-python"
+    prompt_installation "Ruby with rbenv" "dotfiles-ruby"
+    prompt_installation "SDKMAN" "dotfiles-java-sdkman"
+    prompt_installation "NodeJS with NVM" "dotfiles-nodejs"
+    prompt_installation "PHP with phpenv" "dotfiles-php"
+    prompt_installation "Vim with plugins" "dotfiles-vim"
 
     echo 'Setting up oh-my-zsh...'
     curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install | sh -s -- --unattended
