Re-enable cleanup/steps before stowing..

diff --git a/linux/systems/bin/dotfiles-ssh b/linux/systems/bin/dotfiles-ssh
--- a/linux/systems/bin/dotfiles-ssh
+++ b/linux/systems/bin/dotfiles-ssh
@@ -1,11 +1,18 @@
 #!/bin/sh
 
+# This script is used to stow and manage dotfiles for SSH and GNUPG configurations.
+DOTFILES_PATH="$HOME/.dotfiles"
+if [ ! -d "$DOTFILES_PATH" ]; then
+  echo "Error: $DOTFILES_PATH does not exist. Please clone the dotfiles repository first." >&2
+  exit 1
+fi
+
 # Manually stow SSH configs
 mkdir -p $HOME/.ssh
 if [ -f $HOME/.ssh/config ]; then
   mv $HOME/.ssh/config $HOME/.ssh/config.bak
 fi
-ln -sf $PWD/linux/ssh/.ssh/config $HOME/.ssh/config
+ln -sf $DOTFILES_PATH/linux/ssh/.ssh/config $HOME/.ssh/config
 
 # Manually stow GNUPG configs
 # https://gist.github.com/oseme-techguy/bae2e309c084d93b75a9b25f49718f85
@@ -18,8 +25,8 @@ fi
 if [ -f $HOME/.gnupg/gpg-agent.conf ]; then
   mv $HOME/.gnupg/gpg-agent.conf $HOME/.gnupg/gpg-agent.conf.bak
 fi
-ln -sf $PWD/linux/gpg/.gnupg/gpg.conf $HOME/.gnupg/gpg.conf
-ln -sf $PWD/linux/gpg/.gnupg/gpg-agent.conf $HOME/.gnupg/gpg-agent.conf
+ln -sf $DOTFILES_PATH/linux/gpg/.gnupg/gpg.conf $HOME/.gnupg/gpg.conf
+ln -sf $DOTFILES_PATH/linux/gpg/.gnupg/gpg-agent.conf $HOME/.gnupg/gpg-agent.conf
 
 # Check if gpgconf and gpg-connect-agent commands exist
 if command -v gpgconf >/dev/null 2>&1 && command -v gpg-connect-agent >/dev/null 2>&1; then
@@ -33,12 +40,3 @@ else
   echo "Error: gpgconf and/or gpg-connect-agent commands not found." >&2
   exit 1
 fi
-
-read -p "Enter your email address for the SSH key (or press Enter to cancel): " EMAIL
-if [ -z "$EMAIL" ]; then
-    echo "No email provided. SSH key creation will be skipped. Exiting..."
-    exit 0
-fi
-
-ssh-keygen -t ed25519 -C "$EMAIL" -f $HOME/.ssh/id_ed25519 -N ""
-ssh-keygen -t rsa -b 4096 -C "$EMAIL" -f $HOME/.ssh/id_rsa -N ""
