Attempt to install pre-commit and ensure python is installed before... part 2

diff --git a/linux/zsh/bin/dotfiles-python--pre-commit b/linux/zsh/bin/dotfiles-python--pre-commit
--- a/linux/zsh/bin/dotfiles-python--pre-commit
+++ b/linux/zsh/bin/dotfiles-python--pre-commit
@@ -2,46 +2,39 @@
 
 echo "Installing pre-commit hooks..."
 WORKDIR=$(mktemp -d)
-ORIGINAL_DIR=$(pwd)
-PYENV_FOUND=0
+PYENV_ROOT="$HOME/.pyenv"
 trap 'rm -rf "$WORKDIR"' EXIT
-cd $HOME
 
 setup() {
   # Check if pre-commit is installed
   if command -v pre-commit &> /dev/null; then
-      echo "pre-commit is installed. Exiting..."
+      echo "pre-commit is already installed. Exiting..."
       exit 0
   else
       echo "pre-commit not found. Installing pre-commit..."
-      pip install --user pre-commit
+      if ! pip install --user pre-commit; then
+          echo "Error: Failed to install pre-commit." >&2
+          exit 1
+      fi
   fi
 }
 
-# Ensure pip or pip3 is installed. Otherwise tell the user to execure dotfiles-python
+# Ensure pip or pip3 is installed. Otherwise, prompt the user to install Python
 if ! command -v pip &> /dev/null && ! command -v pip3 &> /dev/null; then
     echo "pip or pip3 not found."
     echo "Checking pyenv installation..."
-    if [ -d "$HOME/.pyenv" ]; then
+    if [ -d "$PYENV_ROOT" ]; then
         echo "pyenv found."
         # Temporarily load pyenv
-        export PHPENV_ROOT="$HOME/.phpenv"
-        if [ -d "$PHPENV_ROOT" ]; then
-          PYENV_FOUND=1
-          export PATH="$PHPENV_ROOT/bin:$PATH"
-          eval "$(phpenv init -)"
-        fi
-        if [ $PYENV_FOUND -eq 1 ]; then
-            # Use python from system
-            pyenv global system
-            pyenv rehash
-            setup
-        else
-            echo "ERROR Level 2: pyenv not found. Please install pyenv first."
-            exit 1
-        fi
+        export PATH="$PYENV_ROOT/bin:$PATH"
+        eval "$(pyenv init -)"
+
+        # Use system Python
+        pyenv global system
+        pyenv rehash
+        setup
     else
-        echo "ERROR Level 1: pyenv not found. Please install pyenv first."
+        echo "Error: pyenv not found. Please install pyenv first." >&2
         exit 1
     fi
 else
